FROM golang:1.19-alpine AS builder

WORKDIR /app
COPY . .
RUN go build -o order-app cmd/order-app/main.go
ENTRYPOINT ./order-app

FROM alpine
WORKDIR /app

COPY --from=builder /app/order-app .
ENTRYPOINT ["/app/order-app"]

