FROM golang:1.19-alpine AS builder

WORKDIR /app
COPY . .
RUN go build -o database-initializer cmd/database-initializer/main.go
ENTRYPOINT ./database-initializer

FROM alpine
WORKDIR /app
# need to copy data and .env
COPY --from=builder /app .
ENTRYPOINT ["/app/database-initializer"]

